### PR TITLE
Added basic support for Google Analytics

### PR DESCRIPTION
**Pull request by lasharor**

### CODE REVIEW

**Comment by lasharor** [comment]
Not sure how to do this properly, but this code should be added with env to change the UA-CODE in order to make google analytics work.

Tested this successfully on my website.

**Comment by lucascervera** [comment]
> Not sure how to do this properly, but this code should be added with env to change the UA-CODE in order to make google analytics work.
> 
> Tested this successfully on my website.

This worked for me as well. Thanks.

**Comment by transitive-bullshit** [comment]
I think this works better as a code example than something which is supported out of the box.

Maybe we can add it to the docs instead?

**Comment by PersistVenture** [comment]
@lasharor  
added below code in pagehead.tsx:
 <script
            async
            src={`https://www.googletagmanager.com/gtag/js?id=UA-CODE`}
          />
          <script
            dangerouslySetInnerHTML={{
              __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'UA-CODE', {
              page_path: window.location.pathname,
            });
          `,
            }}
          />
          
          
  and update UA-Code in .env file:
  UA-CODE = "G-XXXXXXXXXX"
  
  but its not working on my site? Is there anything more I have to write?
  
  Please suggest and help.

**Pull request closed without merging**
