### PR TITLE
Improve redis documentation

### PR DESCRIPTION
**Pull request by Vadorequest**
Documentation about how to setup Redis (GHA), and how to configure env variables on Vercel.

Also mention Redis Labs to make it easier to get started with Redis for free.

### CODE REVIEW

**Review by transitive-bullshit — APPROVED** [review]
This looks great @Vadorequest. Thanks!

I'll probably tweak some of the wording a bit, but overall it looks great.

**Comment by Vadorequest** [comment]
Thanks for merging it in a timely manner! And yeah, don't hesitate to tweak things around 😉

**Comment by Kmfernan5** [comment]
Am I missing any Environment Variables?

https://share.getcloudapp.com/04uQlj8v

**Comment by transitive-bullshit** [comment]
@Kmfernan5 you should not be sharing any of these environment variables publicly. They're supposed to be private.

**Pull request merged**
